import { Category, Product, StoreMenu } from "./types"

// Stores list for reference
export const STORES_LIST = [
  { id: "1", name: "Hari har Restaurant" },
  { id: "2", name: "Shiva Nasta House" },
  { id: "3", name: "Venkatesh" },
  { id: "4", name: "vv demo" },
]

// Categories per store
export const CATEGORIES: Category[] = [
  { id: "cat1", name: "Starters", description: "Appetizers and snacks" },
  { id: "cat2", name: "Main Course", description: "Rice and curry dishes" },
  { id: "cat3", name: "Beverages", description: "Drinks and refreshments" },
  { id: "cat4", name: "Desserts", description: "Sweet dishes" },
  { id: "cat5", name: "Snacks", description: "Light bites" },
  { id: "cat6", name: "South Indian", description: "Dosa, Idli, etc." },
  { id: "cat7", name: "Fast Food", description: "Quick bites" },
]

// Products data
export const PRODUCTS: Product[] = [
  // Hari har Restaurant products
  {
    id: "p1",
    name: "Paneer Tikka",
    description: "Grilled cottage cheese with spices",
    price: 250,
    categoryId: "cat1",
    categoryName: "Starters",
    storeId: "1",
    storeName: "Hari har Restaurant",
    isAvailable: true,
    createdAt: "2026-02-07",
  },
  {
    id: "p2",
    name: "Butter Naan",
    description: "Soft bread baked in tandoor",
    price: 40,
    categoryId: "cat2",
    categoryName: "Main Course",
    storeId: "1",
    storeName: "Hari har Restaurant",
    isAvailable: true,
    createdAt: "2026-02-07",
  },
  {
    id: "p3",
    name: "Dal Makhani",
    description: "Creamy black lentils",
    price: 180,
    categoryId: "cat2",
    categoryName: "Main Course",
    storeId: "1",
    storeName: "Hari har Restaurant",
    isAvailable: true,
    createdAt: "2026-02-07",
  },
  {
    id: "p4",
    name: "Mango Lassi",
    description: "Sweet mango yogurt drink",
    price: 80,
    categoryId: "cat3",
    categoryName: "Beverages",
    storeId: "1",
    storeName: "Hari har Restaurant",
    isAvailable: true,
    createdAt: "2026-02-07",
  },
  {
    id: "p5",
    name: "Gulab Jamun",
    description: "Deep fried milk dumplings in sugar syrup",
    price: 60,
    categoryId: "cat4",
    categoryName: "Desserts",
    storeId: "1",
    storeName: "Hari har Restaurant",
    isAvailable: false,
    createdAt: "2026-02-07",
  },
  
  // Shiva Nasta House products
  {
    id: "p6",
    name: "Samosa",
    description: "Crispy fried pastry with potato filling",
    price: 15,
    categoryId: "cat5",
    categoryName: "Snacks",
    storeId: "2",
    storeName: "Shiva Nasta House",
    isAvailable: true,
    createdAt: "2026-02-09",
  },
  {
    id: "p7",
    name: "Chai",
    description: "Traditional Indian tea",
    price: 20,
    categoryId: "cat3",
    categoryName: "Beverages",
    storeId: "2",
    storeName: "Shiva Nasta House",
    isAvailable: true,
    createdAt: "2026-02-09",
  },
  {
    id: "p8",
    name: "Kachori",
    description: "Spicy lentil filled pastry",
    price: 25,
    categoryId: "cat5",
    categoryName: "Snacks",
    storeId: "2",
    storeName: "Shiva Nasta House",
    isAvailable: true,
    createdAt: "2026-02-09",
  },
  {
    id: "p9",
    name: "Jalebi",
    description: "Sweet crispy spirals",
    price: 40,
    categoryId: "cat4",
    categoryName: "Desserts",
    storeId: "2",
    storeName: "Shiva Nasta House",
    isAvailable: true,
    createdAt: "2026-02-09",
  },
  
  // Venkatesh products
  {
    id: "p10",
    name: "Masala Dosa",
    description: "Crispy rice crepe with potato filling",
    price: 80,
    categoryId: "cat6",
    categoryName: "South Indian",
    storeId: "3",
    storeName: "Venkatesh",
    isAvailable: true,
    createdAt: "2026-02-09",
  },
  {
    id: "p11",
    name: "Idli Sambar",
    description: "Steamed rice cakes with lentil soup",
    price: 60,
    categoryId: "cat6",
    categoryName: "South Indian",
    storeId: "3",
    storeName: "Venkatesh",
    isAvailable: true,
    createdAt: "2026-02-09",
  },
  {
    id: "p12",
    name: "Filter Coffee",
    description: "Traditional South Indian filter coffee",
    price: 30,
    categoryId: "cat3",
    categoryName: "Beverages",
    storeId: "3",
    storeName: "Venkatesh",
    isAvailable: true,
    createdAt: "2026-02-09",
  },
  {
    id: "p13",
    name: "Vada",
    description: "Crispy lentil fritters",
    price: 40,
    categoryId: "cat6",
    categoryName: "South Indian",
    storeId: "3",
    storeName: "Venkatesh",
    isAvailable: false,
    createdAt: "2026-02-09",
  },
  
  // vv demo products
  {
    id: "p14",
    name: "Pizza",
    description: "Cheese pizza with toppings",
    price: 200,
    categoryId: "cat7",
    categoryName: "Fast Food",
    storeId: "4",
    storeName: "vv demo",
    isAvailable: true,
    createdAt: "2026-02-09",
  },
  {
    id: "p15",
    name: "Burger",
    description: "Veg burger with fries",
    price: 120,
    categoryId: "cat7",
    categoryName: "Fast Food",
    storeId: "4",
    storeName: "vv demo",
    isAvailable: true,
    createdAt: "2026-02-09",
  },
  {
    id: "p16",
    name: "Cold Coffee",
    description: "Iced coffee with cream",
    price: 90,
    categoryId: "cat3",
    categoryName: "Beverages",
    storeId: "4",
    storeName: "vv demo",
    isAvailable: true,
    createdAt: "2026-02-09",
  },
]
